#!/bin/bash
set -e

# check if a version number is provided
if [ -z "$1" ]; then
  echo "usage: ./release <version>"
  exit 1
fi

# check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
  echo "there are uncommitted changes. please commit or stash them before releasing."
  exit 2
fi

# check for being on the main branch
if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
  echo "you must be on the main branch to release."
  exit 3
fi

# check if the current commit is already tagged
if [ -n "$(git tag --points-at HEAD)" ]; then
  echo "the current commit is already tagged. if you still want to tag and release, you must do so manually."
  exit 4
fi

VERSION=$1
VERSION_FILE="lib/stable/version.rb"

# update the version file
echo "updating version to $VERSION in $VERSION_FILE"
sed -i.bak "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" $VERSION_FILE
rm ${VERSION_FILE}.bak

# update Gemfile.lock and verify the example task
echo "re-bundling and running verification task..."
bundle install && rake stable:example

echo "building gem..."
gem build stable.gemspec

git add --all
git commit -m "$VERSION"
git tag $VERSION
git push && git push --tags

echo "release script finished."

gem push stable-$VERSION.gem
