#!/bin/bash
set -e

# check if a version number is provided
if [ -z "$1" ]; then
  echo "Usage: ./release <version>"
  exit 1
fi

VERSION=$1
VERSION_FILE="lib/stable/version.rb"

# update the version file
echo "updating version to $VERSION in $VERSION_FILE"
sed -i.bak "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" $VERSION_FILE
rm ${VERSION_FILE}.bak

# update Gemfile.lock and verify the example task
echo "re-bundling and running verification task..."
bundle install && rake stable:example

echo "building gem..."
gem build stable.gemspec

git add --all
git commit -m "$VERSION"
git tag $VERSION
git push && git push --tags

echo "release script finished."
